// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nekizz/vmo-demo-project/internal/file_processor (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination internal/file_processor/mock.go -package=file_processor github.com/nekizz/vmo-demo-project/internal/file_processor Service
//

// Package file_processor is a generated GoMock package.
package file_processor

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CheckSum mocks base method.
func (m *MockService) CheckSum(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSum", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSum indicates an expected call of CheckSum.
func (mr *MockServiceMockRecorder) CheckSum(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSum", reflect.TypeOf((*MockService)(nil).CheckSum), arg0)
}

// CountFileLine mocks base method.
func (m *MockService) CountFileLine(arg0 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFileLine", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFileLine indicates an expected call of CountFileLine.
func (mr *MockServiceMockRecorder) CountFileLine(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFileLine", reflect.TypeOf((*MockService)(nil).CountFileLine), arg0)
}
