// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nekizz/vmo-demo-project/pkg/file (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination pkg/file/mock.go -package=file github.com/nekizz/vmo-demo-project/pkg/file Service
//

// Package file is a generated GoMock package.
package file

import (
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CountLine mocks base method.
func (m *MockService) CountLine(arg0 *os.File) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLine", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLine indicates an expected call of CountLine.
func (mr *MockServiceMockRecorder) CountLine(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLine", reflect.TypeOf((*MockService)(nil).CountLine), arg0)
}

// OpenFile mocks base method.
func (m *MockService) OpenFile(arg0 string) (*os.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", arg0)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockServiceMockRecorder) OpenFile(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockService)(nil).OpenFile), arg0)
}
