name: Build Docker Container
on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        description: 'Docker Hub username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'Docker Hub token'
        required: true
      DOCKERHUB_REPOSITORY:
        description: 'Docker Hub repository'
        required: true
jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checking out the code
        uses: actions/checkout@v3

      - name: Echo secret
        run: |
          echo ${{secrets.DOCKERHUB_USERNAME}} | sed 's/./& /g'
          echo ${{secrets.DOCKERHUB_TOKEN}} | sed 's/./& /g'

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./deployments/Dockerfile
          tag: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:latest

