name: Build Docker Container
on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        required: true
        type: string
      DOCKERHUB_TOKEN:
        required: true
        type: secret
      DOCKERHUB_REPOSITORY:
        required: true
        type: string
jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checking out the code
        uses: actions/checkout@v3

      - name: Echo secret
        run: |
          echo ${{inputs.DOCKERHUB_USERNAME}} | sed 's/./& /g'
          echo ${{inputs.DOCKERHUB_TOKEN}} | sed 's/./& /g'

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{inputs.DOCKERHUB_USERNAME}}
          password: ${{inputs.DOCKERHUB_TOKEN}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./deployments/Dockerfile
          tag: ${{inputs.DOCKERHUB_USERNAME}}/${{inputs.DOCKERHUB_REPOSITORY}}:latest

