name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-code:
    uses: ./.github/workflows/build_code.yaml

  echo-flow:
    steps:
      - name: Echo secret
        run: |
          echo ${{secrets.DOCKERHUB_USERNAME}} | sed 's/./& /g'
          echo ${{secrets.DOCKERHUB_TOKEN}} | sed 's/./& /g'

  build-docker:
    if: github.event_name == 'push'
    uses: ./.github/workflows/build_docker.yaml
    needs: [build-code]
    permissions:
      id-token: write
      contents: read
    with:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
