name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-code:
    uses: ./.github/workflows/build_code.yaml

  build-docker:
    if: github.event_name == 'push'
    uses: ./.github/workflows/build_docker.yaml
    needs: [build-code]
